name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  RENOVATE_VERSION: 37.432.0 # renovate: datasource=npm depName=renovate
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
        name: check renovate config.js
        with:
          validator_version: ${{ env.RENOVATE_VERSION }}
          config_file_path: config.js
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
        name: check local renovate.json
        with:
          validator_version: ${{ env.RENOVATE_VERSION }}
          config_file_path: .renovaterc.json