name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}