name: Renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
  schedule:
    - cron: '0/15 * * * *'
env:
  RENOVATE_VERSION: 38.130.3@sha256:8c30b750ac2b0301c2d6003e87b381e1388c3b1b4b6d79bc88280b7b937dc68d # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8ce0fe8066eb6b16e1bf499b21bc96e5ccd962a4 # v40.2.3
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: debug
